version : '3'

services:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 8306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80


#phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    environment:
#     - PMA_ARBITRARY=1
#    restart: always
#    ports:
#     - 8085:8085
#    volumes:
#     - /sessions
